2022-06-10 16:10:16.417 [error] <0.302.0> CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.SendMessage was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:12:20.686 [error] <0.300.0> CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.Worker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:13:28.847 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.Worker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:14:43.988 [error] <0.300.0> CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.Worker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:15:35.343 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.Worker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:16:59.262 [error] <0.292.0> CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.Worker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:17:09.565 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.Worker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:18:06.293 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.Worker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-10 16:43:14.351 [error] <0.304.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um nome vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 24
2022-06-10 16:43:14.361 [error] <0.304.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um nome vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 24
2022-06-10 16:43:14.361 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um nome vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 24 in context child_terminated
2022-06-10 16:45:56.982 [error] <0.304.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:45:56.989 [error] <0.304.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:45:56.989 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:45:59.181 [error] <0.322.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:45:59.181 [error] <0.322.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:45:59.181 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.322.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:46:01.039 [error] <0.336.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:01.039 [error] <0.336.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:01.039 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.336.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:46:02.894 [error] <0.350.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:02.895 [error] <0.350.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:02.895 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.350.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:46:04.615 [error] <0.364.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:04.615 [error] <0.364.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:04.616 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.364.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:46:04.616 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.364.0> exit with reason reached_max_restart_intensity in context shutdown
2022-06-10 16:46:29.958 [error] <0.304.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:29.965 [error] <0.304.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:29.965 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:46:31.318 [error] <0.322.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:31.318 [error] <0.322.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:31.319 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.322.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:46:36.646 [error] <0.336.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:36.646 [error] <0.336.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:36.646 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.336.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:46:38.599 [error] <0.350.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:38.599 [error] <0.350.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:46:38.599 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.350.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:48:30.308 [error] <0.304.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:30.310 [error] <0.304.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:30.310 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:48:31.500 [error] <0.322.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:31.500 [error] <0.322.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:31.500 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.322.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:48:32.958 [error] <0.336.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:32.958 [error] <0.336.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:32.958 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.336.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:48:33.535 [error] <0.350.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:33.535 [error] <0.350.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:48:33.535 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.350.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:48:33.536 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.350.0> exit with reason reached_max_restart_intensity in context shutdown
2022-06-10 16:49:18.019 [error] <0.304.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:18.025 [error] <0.304.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:18.025 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:49:18.645 [error] <0.322.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:18.645 [error] <0.322.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:18.645 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.322.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:49:19.263 [error] <0.336.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:19.263 [error] <0.336.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:19.263 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.336.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:49:19.846 [error] <0.350.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:19.846 [error] <0.350.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19
2022-06-10 16:49:19.847 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.350.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.Worker':handle_cast/2 line 19 in context child_terminated
2022-06-10 16:49:19.847 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.Worker' started with 'Elixir.ChatRabbitmq.Worker':start_link(nil) at <0.350.0> exit with reason reached_max_restart_intensity in context shutdown
2022-06-13 14:50:27.265 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module ChatRabbitmq.WorkerReceiveMessage was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2022-06-13 14:50:46.289 [error] <0.310.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerReceiveMessage' started with 'Elixir.ChatRabbitmq.WorkerReceiveMessage':start_link(nil) at undefined exit with reason {already_started,<0.311.0>} in context start_error
2022-06-13 14:50:46.290 [error] <0.308.0> CRASH REPORT Process <0.308.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ChatRabbitmq.WorkerReceiveMessage',{already_started,<0.311.0>}}},{'Elixir.ChatRabbitmq.Application',start,[normal,[]]}} in application_master:init/4 line 142
2022-06-13 14:51:08.683 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerReceiveMessage' started with 'Elixir.ChatRabbitmq.WorkerReceiveMessage':start_link(nil) at undefined exit with reason {already_started,<0.304.0>} in context start_error
2022-06-13 14:51:08.683 [error] <0.301.0> CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ChatRabbitmq.WorkerReceiveMessage',{already_started,<0.304.0>}}},{'Elixir.ChatRabbitmq.Application',start,[normal,[]]}} in application_master:init/4 line 142
2022-06-13 14:53:08.169 [error] <0.302.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerReceiveMessage' started with 'Elixir.ChatRabbitmq.WorkerReceiveMessage':start_link(nil) at undefined exit with reason {already_started,<0.303.0>} in context start_error
2022-06-13 14:53:08.169 [error] <0.300.0> CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ChatRabbitmq.WorkerReceiveMessage',{already_started,<0.303.0>}}},{'Elixir.ChatRabbitmq.Application',start,[normal,[]]}} in application_master:init/4 line 142
2022-06-13 15:15:29.001 [error] <0.304.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:29.014 [error] <0.304.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:29.015 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerSendMessage' started with 'Elixir.ChatRabbitmq.WorkerSendMessage':start_link(nil) at <0.304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19 in context child_terminated
2022-06-13 15:15:38.093 [error] <0.330.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:38.093 [error] <0.330.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:38.094 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerSendMessage' started with 'Elixir.ChatRabbitmq.WorkerSendMessage':start_link(nil) at <0.330.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19 in context child_terminated
2022-06-13 15:15:39.173 [error] <0.337.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:39.175 [error] <0.337.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:39.176 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerSendMessage' started with 'Elixir.ChatRabbitmq.WorkerSendMessage':start_link(nil) at <0.337.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19 in context child_terminated
2022-06-13 15:15:39.828 [error] <0.356.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:39.829 [error] <0.356.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:39.830 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerSendMessage' started with 'Elixir.ChatRabbitmq.WorkerSendMessage':start_link(nil) at <0.356.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19 in context child_terminated
2022-06-13 15:15:40.404 [error] <0.365.0> gen_server worker terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:40.405 [error] <0.365.0> CRASH REPORT Process worker with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19
2022-06-13 15:15:40.406 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerSendMessage' started with 'Elixir.ChatRabbitmq.WorkerSendMessage':start_link(nil) at <0.365.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Informe um valor vÃ¡lido!!">>} in 'Elixir.ChatRabbitmq.WorkerSendMessage':handle_cast/2 line 19 in context child_terminated
2022-06-13 15:15:40.406 [error] <0.303.0> Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerSendMessage' started with 'Elixir.ChatRabbitmq.WorkerSendMessage':start_link(nil) at <0.365.0> exit with reason reached_max_restart_intensity in context shutdown
2022-06-13 15:23:13.841 [error] <0.309.0>@Elixir.IO:inspect Supervisor 'Elixir.ChatRabbitmq.Supervisor' had child 'Elixir.ChatRabbitmq.WorkerReceiveMessage' started with 'Elixir.ChatRabbitmq.WorkerReceiveMessage':start_link(nil) at undefined exit with reason call to undefined function 'Elixir.IO':inspect() in context start_error
2022-06-13 15:23:13.842 [error] <0.307.0> CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ChatRabbitmq.WorkerReceiveMessage',{undef,[{'Elixir.IO',inspect,[],[]},{'Elixir.ChatRabbitmq.WorkerReceiveMessage',init,1,[{file,"lib/chat_rabbitmq/worker_receive_message.ex"},{line,5}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,848}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,811}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{'Elixir.ChatRabbitmq.Application',start,[normal,[]]}} in application_master:init/4 line 142
